### ISSUE TITLE
Version 2.16.7.1 is out of date 

### ISSUE THREAD

**Issue by ihordyrman** [dittodhole/chocolatey-rescuetime#6]
The latest version is 3.1.1.2. Could you please update it?

**Comment by dittodhole** [comment]
Hi there,

thanks for reporting.

The latest build (https://ci.appveyor.com/project/dittodhole/chocolatey-rescuetime/builds/43197333) did not get pushed to chocolatey, due to conflicts, but is available on myget ever since.

Anyway, just triggered another build (https://ci.appveyor.com/project/dittodhole/chocolatey-rescuetime/builds/44549497) - should be fine now.

Best
Andreas

**Comment by dittodhole** [comment]
Hi again & reopening ...

Sad to see that the validation fails 😢  Anyway, as suggested in [this thread](http://disq.us/p/2qj0ep0), there's a new install location.

As I am currently not maintaining this project anymore, I am open to contributions.


Best
Andreas

**Comment by dittodhole** [comment]
Just pushed a [new version](https://community.chocolatey.org/packages/rescuetime/3.1.1.2), awaiting approval.

**Comment by ihordyrman** [comment]
Hey, sorry for the late response.
Thank you for changing the URL.
